# Deployment settings
base_url = "https://solhvemjsun.github.io"
output_dir = "public"
hard_link_static = false
compile_sass = true
minify_html = true
ignored_content = []
ignored_static = []

# Basic Info
title = "Sol's Blog"
description = "Fiat Lux"
author = "Sol"

# Language Settings
default_language = "en"

# Feeds settings
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  {name = "tags", feed = true}, # Feeds for each tag
]

build_search_index = true
generate_sitemap = true
generate_robots_txt = true


[markdown]

# Code highlights
highlight_code = true
highlight_theme = "nord" # to change
error_on_missing_highlight = false

render_emoji = true
external_links_target_blank = true # Wether to open the link in new page or not


[search]
include_title = true
include_description = true
include_date = false
include_path = true
include_content = true


[extra]
# referring to https://www.getzola.org/themes/neovim-theme/
blog_name = "Sol's Blog" # The webpage title

background-image = "assets/background.jpg" # The background for blogpage

[languages.cn]
title  = "献之的博客"
description = "Fiat Lux"

generate_feeds = true
build_search_index = false

[languages.cn.translations]
summary = "我的博客"
